2020-08-18 18:08:46,950 [1] INFO  Microsoft.Hosting.Lifetime - Now listening on: https://localhost:5001
2020-08-18 18:08:47,043 [1] INFO  Microsoft.Hosting.Lifetime - Now listening on: http://localhost:5000
2020-08-18 18:08:47,072 [1] INFO  Microsoft.Hosting.Lifetime - Application started. Press Ctrl+C to shut down.
2020-08-18 18:08:47,119 [1] INFO  Microsoft.Hosting.Lifetime - Hosting environment: Development
2020-08-18 18:08:47,198 [1] INFO  Microsoft.Hosting.Lifetime - Content root path: D:\code\x\X.Micro\X.Micro.Service.ServiceA\X.Micro.Service.ServiceA
2020-08-18 18:32:35,603 [1] INFO  Microsoft.Hosting.Lifetime - Now listening on: https://localhost:19000
2020-08-18 18:32:35,625 [1] INFO  Microsoft.Hosting.Lifetime - Application started. Press Ctrl+C to shut down.
2020-08-18 18:32:35,633 [1] INFO  Microsoft.Hosting.Lifetime - Hosting environment: Development
2020-08-18 18:32:35,640 [1] INFO  Microsoft.Hosting.Lifetime - Content root path: D:\code\x\X.Micro\X.Micro.Service.ServiceA\X.Micro.Service.ServiceA
