2020-08-18 18:41:06,512 [1] INFO  Microsoft.Hosting.Lifetime - Now listening on: https://localhost:19010
2020-08-18 18:41:06,528 [1] INFO  Microsoft.Hosting.Lifetime - Application started. Press Ctrl+C to shut down.
2020-08-18 18:41:06,535 [1] INFO  Microsoft.Hosting.Lifetime - Hosting environment: Development
2020-08-18 18:41:06,543 [1] INFO  Microsoft.Hosting.Lifetime - Content root path: D:\code\x\X.Micro\X.Micro.Client.ClientA\X.Micro.Client.ClientA
